### ISSUE TITLE
buycraft/enjin/minecraftmarket command compatibility

### ISSUE THREAD

**Issue by kinggoesgaming** [Radical-Delta/MinersHandouts#10]
Add `/buy`, `/shop` compatibility layer for users used to other platforms to use minershandouts command for buying. As the command is an optional registration on the server owner's part a config option is needed.

**Comment by turtledude01** [comment]
When doing this, there should be a plugin only config option to disable this

**Comment by kinggoesgaming** [comment]
That's what the plan is as it's only on the plugin side
